apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: global
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql # Certifique-se de que este caminho existe na sua VM/EC2

